# Fase de construcción
FROM node:20 AS build
WORKDIR /app

# Copiar solo package.json primero para aprovechar cache
COPY package*.json ./
RUN npm install

# Copiar el resto del proyecto
COPY . .
RUN npm run build

# Fase de producción con Nginx
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

