name: Deploy Portafolio

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📡 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/Portafolio || git clone https://github.com/Lemorax99/Portafolio.git && cd Portafolio
            git pull origin main
            docker compose down
            docker compose up -d --build